# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BlogBundle\Entity\User:
            algorithm: plaintext #replace for a sha512 later
            encode_as_base64: false
            iterations: 1

    providers:
        our_db_provider:
            entity:
                class: BlogBundle:User
                property: username
                property: password

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                provider: our_db_provider
                login_path: bundle_login
                check_path: bundle_login_check
                default_target_path: blog_homepage
            pattern:    ^/
            logout:
                path:   bundle_logout
                target: bundle_login

    access_control:
        - { path: ^/administration,       roles: IS_AUTHENTICATED_FULLY  }
        - { path: ^/,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
