# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BlogBundle\Entity\User:
            algorithm: plaintext
            # encode_as_base64: false
            # iterations: 1

    providers:
        in_memory:
            memory: ~

    providers:
        our_db_provider:
            entity:
                class: BlogBundle:User
                property: mail
                property: password

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: blog_homepage
            pattern:    ^/
            logout:
                path:   admin_logout
                target: admin_login

    access_control:
        - { path: bundle_login,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: bundle_login_check,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: bundle_logout,       role: ROLE_ADMIN }
        - { path: ^/administration,       role: ROLE_ADMIN }
        - { path: ^/,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
