<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
  public function findOne($id){

    try{
      $article = $this->createQueryBuilder('p')
        ->where('p.id = :id')
        ->setParameter('id',$id)
        ->getQuery()
        ->getSingleResult();
    }
    catch(\Exception $ex){
      $article = null;
    }

    return $article;
  }

  public function getByNumber($number)
  {
	   $query = $this->createQueryBuilder('post')
		    ->setMaxResults($number)
        ->orderBy('post.id', 'DESC')
        ->getQuery();

        return $query->getResult();
  }

}
