blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Articles:articles }

bundle_articles:
  path:     /articles
  defaults: { _controller: BlogBundle:Articles:articles }

bundle_article:
  path:     /articles/{id}
  defaults: { _controller: BlogBundle:Articles:article }
  requirements:
    id: \d+

bundle_newArticle:
  path:     /article/new
  defaults: { _controller: BlogBundle:Articles:new }

bundle_newCategory:
  path:     /category/new
  defaults: { _controller: BlogBundle:Categories:new }

bundle_newTag:
  path:     /tag/new
  defaults: { _controller: BlogBundle:Tags:new }


bundle_categories:
  path:     /categories
  defaults: { _controller: BlogBundle:Categories:categories }
