blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Articles:articles }

bundle_articles:
  path:     /articles
  defaults: { _controller: BlogBundle:Articles:articles }

bundle_article:
  path:     /articles/{id}
  defaults: { _controller: BlogBundle:Articles:article }
  requirements:
    id: \d+

bundle_categories:
  path:     /categories
  defaults: { _controller: BlogBundle:Categories:categories }

#--------------#
#     ADMIN    #
#--------------#

bundle_newArticle:
  path:     /administration/article/new
  defaults: { _controller: BlogBundle:Articles:new }

bundle_newCategory:
  path:     /administration/category/new
  defaults: { _controller: BlogBundle:Categories:new }

bundle_newTag:
  path:     /administration/tag/new
  defaults: { _controller: BlogBundle:Tags:new }

bundle_admin:
  path:     /administration/tag/new
  defaults: { _controller: BlogBundle:Articles:admin }

#--------------#
#     LOGIN    #
#--------------#

bundle_login:
  path: /login
  defaults: { _controller: BlogBundle:Security:login }

bundle_login_check:
  path: /login_check

bundle_logout:
  path: /logout
