blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

bundle_articles:
  path:     /articles
  defaults: { _controller: BlogBundle:Articles:articles }

bundle_article:
  path:     /articles/{id}
  defaults: { _controller: BlogBundle:Articles:article }
  requirements:
    id: \d+

bundle_form:
  path:     /new
  defaults: { _controller: BlogBundle:Articles:new }
